[package]
name = "unpack-crates"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Unpack crates"
homepage = "https://zero-company.pages.dev/"
repository = "https://github.com/zero-company/zero-community"
readme = "./../../../README.md"

[dependencies]
anyhow = { version = "1.0.75" }
tar = { version = "0.4.40" }
fs_extra = { version = "1.3.0" }
